public class DNASequence {
    // TODO remove hardcoded value
    private String sequence = "GTTTTAGAGCTATGCTGTTTTGAATGGTCCCAAAACTGCGCTGGTTGATTTCTTCTTGCGCTTTTTGTTTTAGAGCTATGCTGTTTTGAATGGTCCCAAAACTTATATGAACATAACTCAATTTGTAAAAAAGTTTTAGAGCTATGCTGTTTTGAATGGTCCCAAAACAGGAATATCCGCAATAATTAATTGCGCTCTGTTTTAGAGCTATGCTGTTTTGAATGGTCCCAAAACAGTGCCGAGGAAAAATTAGGTGCGCTTGGCGTTTTAGAGCTATGCTGTTTTGAATGGTCCCAAAACTAAATTTGTTTAGCAGGTAAACCGTGCTTTGTTTTAGAGCTATGCTGTTTTGAATGGTCCCAAAACTTCAGCACACTGAGACTTGTTGAGTTCCATGTTTTAGAGCTATGCTGTTTTGAATGGTCTCCATTC";;
    public static DNASequence build(String sequenceFile) {
        // read sequence file
        // set sequence
        return new DNASequence();
    }
}
